# Generated by Django 3.2.4 on 2023-10-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_datos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='idUser',
            field=models.AutoField(db_column='idUser', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inicio_sesion',
            name='idUser',
            field=models.AutoField(db_column='idUser', primary_key=True, serialize=False),
        ),
    ]
